<div>
{include file="CRM/common/formButtons.tpl" location="top"}
</div>

<h3>This new form is generated by CRM/Slickgrid/Form/SlickgridBatch.php</h3>

{$form.profile_id.label} {$form.profile_id.html}

<div>
{include file="CRM/common/formButtons.tpl" location="bottom"}
</div>